### ISSUE TITLE
Servicio de Gestion de Profesor

### ISSUE THREAD

**Issue by LuisDev18** [LuisDev18/ApiSchool#3]
Se deberá desarrollar un servicio de tipo Entidad
A continuación, se indican las operaciones y los detalles del contrato Detalle-Profesor.xsd para el Servicio gestión de profesores:

1. Registrar Profesor:
**Request:** 
Este endpoint recibira los siguientes parametros :
- nombre
- apellidoPaterno
- apellidoMaterno
- dni
- celular
- email
- curso
**Response:**
- ServiceStatus
- ProfesorDetalle

2. Listar Profesores :
 **Request:**
 - texto
 - offset
 - limit
 **Response:**:
- ProfesorDetalle
3. Eliminar Profesor:
**Request:**
- id
**Response:**
- ServiceStatus
4. Actualizar Profesor
  **Request:**
- Id
- celular
- curso
- email
  **Response:**
- ServiceStatus
- ProfesorDetalle
5. Este servicio deberá ser agregado en la colección compartida en Postman **Web Services SOAP - Api School** , asegurarse de agregar en el header un **Content-type : text/xml**

**Comment by migueltaipemamani** [comment]
Ok, no tengo comentarios
